name = "Frands - Modded"
author = "Kerazene"
version = "0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c927b78d642a2363bf5b504c593fc0708448f78b1f91062eaa58e6fc45a5d14"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
