name = "Frands - Modded"
author = "Kerazene"
version = "0.0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "413346a4b57e69540ff37f949a2e8ed70964fe86a6895760760997853f288fa6"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
