name = "Frands - Modded"
author = "Kerazene"
version = "0.0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63dfff92e842140b0f05905b72a3a460288451b9f3bc7f805cdd0bf40ea1e298"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
