name = "Frands - Modded"
author = "Kerazene"
version = "0.0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8b59ad7e03de6dba5cd8e651c8424028b881e131024dbdefee44fadfaceaba0"

[versions]
fabric = "0.14.11"
minecraft = "1.19.2"
