name = "Frands - Modded"
author = "Kerazene"
version = "0.0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ef02be7fc75ccda31c3304633479de657aaa7335088c462658d66dce9e1c6a8"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
